In [1]:
import pandas as pd

# Read the CSV file
airbnb_data = pd.read_csv("UserData.csv")

# View the first 5 rows
airbnb_data.head()

,Monthly_Income,Investment_Percentage,Emergency_Fund,"""Debt_Level""","""Investment_Goals""","""Expected_Returns""","""Volatility_Reaction""","""Loss_Reaction""","""Risk_Allocation""","""Company_type""","""Sector_Preference""","""Review_Freq""",Experience_Level,"""Decision_Tools"""
0,"₹50,000–₹1,00,000",10%–20%,"No, but working on it",None or less than 10%,Long-term wealth creation,10%–15%,Stay calm and buy more,increase,Less than 25%,small,Sector-specific,1,2,Extensive
1,"Above ₹1,00,000",Less than 10%,Yes,10%–30%,Short-term gains,10%–15%,Stay calm and buy more,hold,More than 50%,small,Diversified portfolio,3,3,Rarely
2,"Above ₹1,00,000",10%–20%,Yes,10%–30%,Steady returns,Above 15%,Stay calm and buy more,increase,25%–50%,small,General market,3,3,Extensive
3,"₹50,000–₹1,00,000",More than 20%,No,10%–30%,Short-term gains,Be1 10%,Stay calm and buy more,increase,25%–50%,mid,Diversified portfolio,3,2,Sometimes
4,"Be1 ₹50,000",Less than 10%,"No, but working on it",10%–30%,Long-term wealth creation,10%–15%,Stay calm and buy more,sell,25%–50%,mid,General market,3,2,Rarely

In [2]:
import pandas as pd

# Read the CSV file
nifty_data = pd.read_csv("NIFTY 50.csv")

# View the first 5 rows
nifty_data.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,^NSEI,^NSEI,^NSEI,^NSEI,^NSEI
1,Date,NaN,NaN,NaN,NaN,NaN
2,2007-09-17,4494.64990234375,4549.0498046875,4482.85009765625,4518.4501953125,0
3,2007-09-18,4546.2001953125,4551.7998046875,4481.5498046875,4494.10009765625,0
4,2007-09-19,4732.35009765625,4739.0,4550.25,4550.25,0